language: node_js
sudo: false
dist: trusty
node_js:
- 8
cache:
  yarn: true
  directories:
    - node_modules
script: yarn run test:single
after_success:
- ./node_modules/.bin/codecov -e TRAVIS_NODE_VERSION -f coverage/coverage-final.json
